### ISSUE TITLE
Ubuntu repo add command broken

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/RadeonOpenCompute.github.io#2]
The command listed in the install instructions (`wget -qO - http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add - sudo sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ trusty main > /etc/apt/sources.list.d/rocm.list'`) is broken.

Looks like there's a missing linebreak.

Also, I think the more canonical way to write to a file is `echo <text> | sudo tee <file>` rather than `sudo sh -c `echo <text> > <file>`.

**Comment by almson** [comment]
Also please explicitly list the command for 16.04 ('xenial' instead of 'trusty')

**Comment by almson** [comment]
I also received errors:

> W: The repository 'http://packages.amd.com/rocm/apt/debian xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

and

> E: Failed to fetch http://packages.amd.com/rocm/apt/debian/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by almson** [comment]
Looks like other commands are missing linebreaks as well, such as `sudo apt-get update sudo apt-get install rocm`

**Comment by gstoner** [comment]
Thank you for your comments.   16.04 was still experimental in this release, but we will look into your issue with the upcoming update for ROCm 1.2.   

On the install instruction, we will double check them, but I have add link to the latest readme for the Repo-install now which is on GitHub.
